# Generated by Django 5.0 on 2023-12-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_brend_alter_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='img',
        ),
    ]
