# Generated by Django 5.0.2 on 2024-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image_car_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(upload_to='cars/', verbose_name='Car image'),
        ),
    ]
